name: Bonjour
on:
  - push
jobs:
  container-test-job:
      runs-on: ubuntu-22.04
      container:
        image: ghcr.io/cicd-lectures/gitpod:latest
        env:
          NODE_ENV: development
        ports:
          - 80
        volumes:
          - my_docker_volume:/volume_mount
        options: --user=root
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - run: sudo apt-get install cowsay
        - run: ls -l
        - run: cat README.md | cowsay